### ISSUE TITLE
No response from twitch after "node lurker.js"

### ISSUE THREAD

**Issue by wefghjk** [bartosjiri/twitch-lurker-bot#2]
![image](https://user-images.githubusercontent.com/74632890/103455809-0b82e100-4ccf-11eb-97a7-93db84ed60a0.png)

**Comment by D3XX3R** [comment]
Twitch is having issues for some days.
Nothing we can do about it.

**Comment by bartosjiri** [comment]
You can also refer to [Twitch status](https://status.twitch.tv/) in the future.
