### ISSUE TITLE
error: No response from Twitch.

### ISSUE THREAD

**Issue by RoopeAnkka** [bartosjiri/twitch-lurker-bot#5]
Hello,

How can I fix this?

[2021-03-29 12:15:51] Connecting to the Twitch server as user "xxxx"...
[2021-03-29 12:15:51] Joined channel "xxxx".
[12:15] error: No response from Twitch.
[12:15] error: No response from Twitch.

I tried to use the script for several days if it would be a twitch issue. Any fix for that?

**Comment by bartosjiri** [comment]
Hey, 
unfortunately I haven't been able to replicate the problem. 

Are you sure the channels you are trying to connect exist? You can try enabling debug logging for the script to possibly get more information:
- In the `lurker.js` file, edit the object on line 24 as the following:
    ```
    const tmiOptions = {
        connection: {
            reconnect: true,
            secure: true
        },
        identity: {
            username: user,
            password: token
        },
        channels: channels,
        options: {
            debug: true
        }
    }
    ```

**Comment by RoopeAnkka** [comment]
Somehow adding that fixed problem. I really don't know how, I didn't do anything else.

**Comment by RoopeAnkka** [comment]
Is there a possibility to add like !join command to join different raffles based on chat?

**Comment by bartosjiri** [comment]
> 
> 
> Somehow adding that fixed problem. I really don't know how, I didn't do anything else.

I suspect this is related to https://github.com/tmijs/tmi.js/issues/163 & https://github.com/tmijs/tmi.js/issues/211. It was most likely working correctly even before the script modification, showing a false positive error message.

> 
> 
> Is there a possibility to add like !join command to join different raffles based on chat?

No, as it would expand beyond the intended scope of the project and result in an unfair advantage. You are welcome to fork the repository and add this feature to your project.
